apiVersion: batch/v1 
kind: Job 
metadata: 
  name: poi-checker 
spec: 
  template:
    spec:
      containers: 
        - name: poi-checker 
          image: check_poi:latest
          imagePullPolicy: Always
          env:
            - name: ETHEREUM
              valueFrom:
                secretKeyRef:
                  name: mainnet-rpc
                  key: address
            - name: INDEX_NODE_ENDPOINT
              value: http://index-node:8030/graphql
            - name: NO_ZERO_POIS
              value: 'true'
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: graph_db


      restartPolicy: Never
  backoffLimit: 1
